//import React from 'react'

export default function Douala() {
	return (
		<div className="overflow-auto leading-8 hidde_scroll">
			<div className="py-10">
				<h1 className="text-3xl py-2 lg:text-5xl font-bold lg:py-9 text-[#865100]">Duala / Sawa</h1>
				The Duala (or Sawa people) are a Bantu ethnic group of Cameroon. They primarily inhabit the littoral and southwest region of Cameroon and form a portion of the Sawabantu or "coastal people" of Cameroon. They have historically played a highly influential role in Cameroon due to their long contact with Europeans, high rate of education, and wealth gained over centuries as slave traders and landowners.
			</div>
			<div className="py-10">
				The Duala are related to several ethnic groups (or tribes) in the Cameroon Coastal areas, with whom they share a common traditional origin, and similar histories and cultures. These include the Ewodi, the Bodiman, the Pongo, the Bakole, the Bakweri (or Kwe), the Bamboko, the Isubu (Isuwu or Bimbians), the Limba (or Malimba), the Mungo, the Wovea and the Oroko (or Balondo), they are generally known as the SAWA people.
				The Batanga of the region of Kribi could be added to the preceding list as they claim they are descendants of Mbedi and they report some degree of mutual comprehension between their own language and Malimba.
				Moreover, the Oroko language is classified as a Duala language, seems to be closely related to Bakweri (Mokpwe), which is a Duala language.

			</div>
			<div className="py-10">
				Thus the Kundu, Lue,Mbonge, Ekombe, Londo ba Nanga, Londo ba Diko, Ngolo, Bima, Tanga and Koko are Duala peoples.
				The Duala have dominated the others historically, and these other groups all profess some sort of kinship to them. In addition, many other coastal ethnic groups such as Balong, Bakossi and so on — who are culturally and historically more or less related to the Duala — are under Duala influence, and most of these people speak Duala to some extent. Duala is also spoken by a great part of the Bassa and Bakoko people. The word "Duala" may refer to the Duala "proper" or to the whole set of Duala-like tribes or even possibly to some "duala-ized" Bassa, Bakoko or Manenguba tribes.
			</div>
			<div className="py-10">
				<h1 className="text-2xl lg:text-4xl py-5 font-semibold ">History</h1>
				Early Duala history may only be conjectured from oral traditions. The Duala trace their ancestry back to a man named Mbedi, who lived in an area called Bakota in what is today Gabon or the Republic of the Congo. His sons, Ewale and Dibombo, migrated north and reached a place called Pitti on the Dibamba River. Here, the brothers parted ways after a row. Ewale moved to the mouth of the Dibamba with his followers and then northwest to the east bank of Wouri River estuary. Meanwhile, Dibongo and his companions migrated southeast to the Sanaga River and then split up, some heading upstream with Dibongo and others moving downstream with a man named Elimbe. Ewale's people became the Duala, and Dibongo's the Limba.
				According to Duala traditions, the Bakoko and Bassa ethnic groups occupied the Wouri estuary when the Duala arrived. The Duala then drove them inland, a displacement that likely occurred in the late 17th or early 18th century.
				<div className="py-10">
					<h2 className="text-2xl lg:text-4xl py-5 font-semibold ">Early history</h2>
					The Duala emerged by the 16th century as the leading traders on the Cameroonian coast, though the Isubu and Limba did not trail far behind. The earliest Duala merchants were likely chiefs or headmen.
					The Duala had long kept and traded slaves, who lived in separate settlements and performed menial tasks such as cultivation. Slave owners could only trade their slaves to other Duala, however, and owners were responsible for paying their slaves' debts and arranging their marriages. With the Europeans providing such a hungry market, however, these customs gave way. The main Duala villages soon grew into a prospering township named Douala for the people who lived there. The coastal Duala purchased goods and slaves from interior groups such as the Bakweri, Mungo, Bassa and Bakoko. In turn, they sold these items to the Europeans, typically aboard their ships (and later at mainland factories or stores). In exchange, the Europeans provided alcohol, gunpowder, guns, mirrors, shoes, textiles, and tools. Ndumb'a Lobe of the Bell lineage propped himself up in the 19th century as King Bell. Heads of rival sub-lineages soon rivalled him, including the self-styled King Akwa (Ngando Mpondo) in 1814, King Deido (Jim Ekwalla) of the Deido (an Akwa splinter group), and Prince Lock Priso (Kum'a Mbape) of the Bonaberi.
					By the mid-19th century, the British had taken the lead in trade with the Duala. This coincided with the abolition movement, and the Crown employed the traders to end slavery in the Gulf of Guinea. On 10 June 1840 and 7 May 1841, Akwa and Bell became the first to sign anti-slavery treaties. In exchange, the Europeans provided these rulers with annual gifts of alcohol, guns, textiles, and other goods. In addition, the rulers outlawed practices the British viewed as barbaric, such as sacrificing a chief's wives upon his death.
				</div>
				<div className="py-10">
					The British also wanted to mould the Duala to their own concepts of civilization. This meant educating them in Western learning and converting them to Christianity. Alfred Saker opened a mission in Douala in 1845. By 1875, numerous missions and schools sprung up in Douala and other settlements. The early missionaries learned the Duala language and invented a written form for it, as Bible translation was one of their earliest priorities. Cameroonian Pidgin English began to develop at this time.
					Trade dramatically altered Duala society. European goods became status symbols, and some rulers appointed Western traders and missionaries as advisors. A high proportion of Duala grew wealthy through the new trade, and tensions arose between the haves and have-nots. Competition escalated between coastal groups and even between related settlements. Traders exploited this atmosphere and beginning in 1860, German, French, and Spanish merchants had established contacts and weakened the British monopoly. The Duala had gained a virtual hegemony over trade through the Wouri estuary.
					In response to the threat from foreign merchants, the British put pressure on the Duala kings to request British annexation. In 1879, King Akwa sent such a request; Bell followed suit in 1881 (some historians believe that these documents were faked, however). When King Pass All of the Limba ceded his territories to the French, British traders expressed the urgency of annexing the Duala territories to the Crown. In July 1884, however, German explorer Gustav Nachtigal staged a coup by signing land-cessation treaties with Kings Akwa, Bell, and Deido. The British arrived too late and on 28 March 1885 ceded Victoria to Germany.
					<h2 className="text-2xl lg:text-4xl py-5 font-semibold ">German administration</h2>
					Opposition to German rule followed the annexation. Prince Lock Priso still favored the British and staged a rebellion in December 1884. Around this same time, King Bell faced off against his own people, who were largely opposed to the German rule. Bell then found himself up against the other Duala chiefs in the Duala War, which was fought over the killing of a Bonaberi Duala and Bell's alleged refusal to share his profits with the other sub-lineages. Germany stopped the conflict when one of its nationals was killed. Bell survived, but his power had diminished significantly.
					Realising that the Duala would never again follow the rule of a single king, the Germans instead played the competitors against one another. They supported the weaker King Bell to counter the powerful King Akwa. The Germans initially ruled from Douala, which they called Kamerunstadt, but they moved their capital to the Bakweri settlement of Buea in 1901.
					Years of contact with Westerners and a high level of literacy had allowed a literate upper class of clerks, farmers, and traders to emerge. This class were familiar with European law and conventions, which allowed them to pressure the German colonial government with petitions, legal proceedings, and special interest groups to oppose unpopular or unfair policies. A series of these began in 1910, when the German administration initiated a new poll tax, attempted to seize lands in Douala township, and then tried to oust the native population from the town completely. King Bell's successor, King Rudolf Duala Manga Bell tried to rally resistance by sending emissaries to visit the leaders of island groups. Duala Manga Bell had many allies. Cameroonian kings held together. King Bell's closest ally, kindred and best friend was King Ekandjoum Joseph, whom he visited when he was persecuted by the Germans. The latter king resisted and refused until his death to cooperate with the German administration, which he did not trust.
				</div>
			<div className="py-5">
					German pretended that Ibrahim Njoya of the Bamum tipped the Germans off, and Bell and his collaborators were executed in 1914 for high treason.
					British and French administrations
					In 1918, Germany lost World War I, and her colonies became mandates of the League of Nations. France became the new steward of Duala territories.
					The Duala continued to prosper. Though the French had largely stripped their kings of power, almost half of the ethnic group's 15-20,000 members were important traders, plantation managers or owners, chiefs, or clerks in the civil service by the 1930s. The rest of the people were fishermen and farmers. By the 1940s, many Duala had attained prominence as builders, as well, servicing the growing cities of Douala and Victoria .
					The new colonials maintained the German policies of ousting uncooperative rulers and of impressing workers for the plantations. Individuals could opt to pay a fine to avoid the labour, however, which led to a dearth of workers from the wealthier areas. The French thus encouraged people from the interior to move to the coast and work the plantations (settled well away from the influence of the Duala chiefs). These immigrants were primarily Bamileke. The newcomers grew numerically and economically dominant over time, leading to ethnic tensions with the indigenes. By the early 1930s, the Duala were a minority in the town named for them.
					On 19 December 1929, four paramount chiefs sent a petition to the League of Nations asking for independence for the Cameroons. Their largest concern, however, was the return of seized Duala lands. This Duala land problem reached a head in 1925 when the French sold lands on the Joss Plateau that the Germans had appropriated. In response to pressure from the Bell clan, the French offered other territory in compensation. The Bells initially refused, but the Great Depression eventually prompted them to accept the French compromise. The Bells gained land in Bali district, and the French promised not to take any of the Akwa or Deido clans' holdings.
					In the late 1930s, Alexandre Duala Manga Bell had emerged as the unofficial leader of the Duala proper. In 1937, the French expelled the Duala from Akwa town (an area of Douala), although they allowed them to maintain ownership of the land. During World War II, the French and British showed favouritism toward white-owned plantations, and many Duala-owned farms became unprofitable . Meanwhile, other Cameroonian ethnic groups had caught up to the Duala's lead in education and Westernisation.
			</div>
				At war's end, the United Nations set in motion the decolonisation of Africa. The Duala remained important in this process. For example, many Duala supported the pro-independence Union des Populations du Cameroun party (UPC) when it first formed. Other parties that had either Duala founders or significant backing include the Bloc Démocratique Camerounais (BDC), and Action Nationale (AN).

			</div>
		</div>
	)
}
